### ISSUE TITLE
Configure Development Environment

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_gov#1288]
As a Challenge.gov developer, in order to effectively work with Challenge.gov code, I would like a local dev environment setup.

Acceptance criteria:

- [x] Development environment is configured for working effectively with challenge.gov code
     - [x] @kkrug 
     - [x] @cpreisinger 
     - [x] @danivovich 
     - [x] @stepchud 
     - [x] @stonefilipczak 
     - [x] @bilalhankins

**Comment by jdonis** [comment]
@kkrug Please let me know when you're ready for my assistance

**Comment by kkrug** [comment]
Since we are using one ticket for everyone's dev environment setup, I added checkboxes in the acceptance criteria for each developer. Feel free to check yourself off when you're all set.
