### ISSUE TITLE
Quality Control Plan

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_gov#1290]
As a Challenge.gov development lead, in order to deliver secure and high quality code, I would like to establish ongoing quality control and assurance practices.

Acceptance criteria:

- [x] Review and familiarize with QASP
- [x] Draft Quality Control Plan and share it with PO / PM / COR

**Comment by TCKapGrp** [comment]
Draft is available here: https://docs.google.com/document/d/1fNfn2wfGYBuqfLESOljMtP_4FjxWkcXokbmXzXbWMz0/edit?usp=sharing

I am still waiting for review for clarity and completeness by our Development Leads.  They have provided inputs to the document previous to this request for final review.

**Comment by TCKapGrp** [comment]
Hi @r-bartlett-gsa and @jarahameador , The completed Quality Control Document is located at : https://docs.google.com/document/d/1fNfn2wfGYBuqfLESOljMtP_4FjxWkcXokbmXzXbWMz0/edit?usp=sharing

Per @r-bartlett-gsa request/guidance, there are outstanding comments left in the document.  In addition, per @r-bartlett-gsa , the "Compliance with Governing Standards" metric that is awaiting further guidance from GSA and is not to be finalized. We reviewed and believe we have addressed all your comments from the previous version. Please let me know if I can be helpful during your review of this document. Have a great weekend (and vacation!)
