### ISSUE TITLE
Cloud.gov - Restage Application

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_gov#1292]
As a Challenge.gov engineer, in order to take advantage of the recent Cloud.gov buildpack updates and security fixes, I need to restage or redeploy challenge.gov application.

Acceptance criteria:

- [x] Challenge.gov application is restaged/redeployed following direction provided by cloud.gov
- [x] Establish QA/testing process moving forward for similar redeployment activities
  - [x] Complete QA

> A rolling restage operation is the quickest way to upgrade without incurring downtime. You may still want to leverage your deployment infrastructure to perform the upgrade if you have compliance requirements for redeployment operations.
> 
> You can restage your application by opening the command line and entering the following commands:
> 
>   cf target -o gsa-tts-innovation-challenge -s proxy ; cf restage --strategy rolling challenge-Cproxy
> 
> 
> For more information about the buildpack update(s), please see the following release notes:
> 
>   go_buildpack v1.10.18: https://github.com/cloudfoundry/go-buildpack/releases/tag/v1.10.18
> 
>   python_buildpack v1.8.23: https://github.com/cloudfoundry/python-buildpack/releases/tag/v1.8.23
> 
>   nodejs_buildpack v1.8.24: https://github.com/cloudfoundry/nodejs-buildpack/releases/tag/v1.8.24
> 
>   staticfile_buildpack v1.6.12: https://github.com/cloudfoundry/staticfile-buildpack/releases/tag/v1.6.12
> 
>   java_buildpack v4.68.0: https://github.com/cloudfoundry/java-buildpack/releases/tag/v4.68.0
> 
>   ruby_buildpack v1.10.13: https://github.com/cloudfoundry/ruby-buildpack/releases/tag/v1.10.13
> 
>   php_buildpack v4.6.18: https://github.com/cloudfoundry/php-buildpack/releases/tag/v4.6.18
> 
>   dotnet_core_buildpack v2.4.27: https://github.com/cloudfoundry/dotnet-core-buildpack/releases/tag/v2.4.27
> 
>   r_buildpack v1.2.11: https://github.com/cloudfoundry/r-buildpack/releases/tag/v1.2.11
> 
>   nginx_buildpack v1.2.13: https://github.com/cloudfoundry/nginx-buildpack/releases/tag/v1.2.13
> 
>   binary_buildpack v1.1.11: https://github.com/cloudfoundry/binary-buildpack/releases/tag/v1.1.11
> 
> 
> For more information on keeping your application updated and secure, see:
> https://cloud.gov/docs/getting-started/app-maintenance/
> 
> If you have questions, you can email us at [cloud-gov-support@gsa.gov](mailto:cloud-gov-support@gsa.gov).

**Comment by r-bartlett-gsa** [comment]
Additional information from cloud.gov team:

> Regarding restaging and best practices, linked [here](https://cloud.gov/docs/deployment/app-maintenance/#restaging-your-app) is documentation on this matter. In particular we encourage making a plan for testing those changes when an application is restaged in a [staging or development environment](https://cloud.gov/docs/getting-started/concepts/#spaces) prior to restaging in a production environment.
> Also, [here](https://cloud.gov/docs/deployment/app-maintenance/#avoiding-downtime-during-buildpack-or-app-updates) is some documentation on setting up zero downtime deployments for your application when things such as buildpack updates/maintenance are performed.

**Comment by jdonis** [comment]
I stop the challenge-Cproxy Application after the restage, because it's no longer in use now. 

I created this document for the restage process and QA, if you have any comments please let me know

https://docs.google.com/document/d/1__2WJg-06x7Db959tHtisRyGeGi-dkG4pqI8ruYBQhw/edit?usp=sharing

**Comment by jdonis** [comment]
Document Updated
https://docs.google.com/document/d/1__2WJg-06x7Db959tHtisRyGeGi-dkG4pqI8ruYBQhw/
