### ISSUE TITLE
Dependencies & Dependabot Review

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_gov#1296]
As an engineer, in order to ensure the code and repository is secure and up to date, I would like to understand current dependencies with known vulnerabilities.

Acceptance criteria:

- [x] Review exiting [list of dependencies](https://docs.google.com/spreadsheets/d/1SdOazTY5zIAS2BiLhd1cHdnXIFTypZK58nAwfMZqVQc/edit?usp=sharing)
  - [x] Verify if security status is accurate
  - [x] Update notes and details of the dependencies accordingly
  - [x] Create GitHub issues to be prioritized for critical and medium impact dependencies
- [ ] Review and prioritize existing list of dependabot items
  - [ ] [Challenge_gov dependabot alerts](https://github.com/GSA/Challenge_gov/security/dependabot)
  - [ ] [challenges-and-prizes dependabot alerts](https://github.com/GSA/challenges-and-prizes/security/dependabot)

**Comment by jdonis** [comment]
**Dependencies review and prioritization - 7/12/2024** 
https://docs.google.com/spreadsheets/d/1oFX95BcqN34l2wDU-YIFq-rXDPnb8jW0ZOUnuGQzRNk/edit?usp=sharing

**Dependencies closed during the review**
https://docs.google.com/document/d/1VZ2dD88ARY6iYylKBnn4Eo9MvjsKCvbYAqjwuMalc9o/edit?usp=sharing
