### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_gov#1306]
As a challenge.gov team member and/or stakeholder, in order to understand user needs and enable me to implement / communicate new user capabilities/features, I would like to have visual designs representing user needs and workflows.

Acceptance criteria:

- [x] Following UX/ UI discovery work (including findings report) and prioritization workshop, design wireframes are created for the MVP of the eval capability.  
- [x] Wireframes include responsive views

Tasks:
(Wireframes remaining)
- [x]  User Guide Wireframe
- [x] Contact/Help Wireframe

**Comment by TCKapGrp** [comment]
The current drafts of the wireframes are located at https://www.figma.com/design/VfdBFG8ShVnOStdSNYy9fR/Challenge.Gov-Component-Library?node-id=29-3530&node-type=canvas

I added a Task List for @mhotch24 of the wireframes that I'm aware that are remaining.  @r-bartlett-gsa  and @mhotch24 , let me know and/or add to the task list if there are others.

**Comment by r-bartlett-gsa** [comment]
@TCKapGrp I removed recusal wireframe from the task list. That is completed.
