### ISSUE TITLE
.gov development user can login via IdentitySandbox

### ISSUE THREAD

**Issue by ryanwoldatwork** [GSA/Challenge_gov#131]
Hi,

I was able to get the application running locally, with assets showing (`npm install` from /assets). But, I was unable to auth via the login.gov sandbox.

Thank you, and please advise,

![challenge](https://user-images.githubusercontent.com/64987852/93244138-19235380-f73e-11ea-93d8-9d6e36d38863.png)

How is `private.pem` generated? It is referenced in `/config/dev.exs`.

**Comment by afomi** [comment]
I found https://github.com/GSA/Challenge_gov#private-keys
