### ISSUE TITLE
Process GSA Separation Report

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_gov#1311]
As a Challenge.gov admin, in order to ensure only the active GSA employees have access to the platform, I would like the status of separated employees to be updated accordingly.

Acceptance criteria:

- [x] Review [GSA separation report for May, 2024](https://docs.google.com/spreadsheets/d/10yClCOCXIdqmtsQK9pn-qJCd9B_q2dNx/edit?usp=drive_link&ouid=107603508579633019364&rtpof=true&sd=true) and compare it to Challenge.gov users list
- [x] Update the account status of separated employees as needed
- [x] Document updated accounts

**Comment by r-bartlett-gsa** [comment]
[SOP for Security Log and Separations Report](https://docs.google.com/document/d/1K4ii9-NoTfDdR5f6Ms3yP7PFEInteMXVXR2N-vZgpFU/edit?usp=sharing)

**Comment by lil-ninja** [comment]
Monthly Separation Report for May have been completed.
