### ISSUE TITLE
Cloud.gov - Restage Application

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_gov#1312]
As a Challenge.gov engineer, in order to take advantage of the recent Cloud.gov buildpack updates and security fixes, I need to restage or redeploy challenge.gov application.

Acceptance criteria:

- [x] Challenge.gov application is restaged/redeployed following direction provided by cloud.gov
- [x] Complete QA

> For more information about the buildpack update(s), please see the following release notes:
> 
>   go_buildpack v1.10.19: https://github.com/cloudfoundry/go-buildpack/releases/tag/v1.10.19
> 
>   python_buildpack v1.8.25: https://github.com/cloudfoundry/python-buildpack/releases/tag/v1.8.25
> 
>   nodejs_buildpack v1.8.25: https://github.com/cloudfoundry/nodejs-buildpack/releases/tag/v1.8.25
> 
>   staticfile_buildpack v1.6.13: https://github.com/cloudfoundry/staticfile-buildpack/releases/tag/v1.6.13
> 
>   ruby_buildpack v1.10.15: https://github.com/cloudfoundry/ruby-buildpack/releases/tag/v1.10.15
> 
>   php_buildpack v4.6.19: https://github.com/cloudfoundry/php-buildpack/releases/tag/v4.6.19
> 
>   dotnet_core_buildpack v2.4.28: https://github.com/cloudfoundry/dotnet-core-buildpack/releases/tag/v2.4.28
> 
>   r_buildpack v1.2.12: https://github.com/cloudfoundry/r-buildpack/releases/tag/v1.2.12
> 
>   nginx_buildpack v1.2.14: https://github.com/cloudfoundry/nginx-buildpack/releases/tag/v1.2.14
> 
>   binary_buildpack v1.1.12: https://github.com/cloudfoundry/binary-buildpack/releases/tag/v1.1.12
>

**Comment by jdonis** [comment]
Restage and QA done!

Process reference 
https://docs.google.com/document/d/1__2WJg-06x7Db959tHtisRyGeGi-dkG4pqI8ruYBQhw/edit?usp=sharing
