### ISSUE TITLE
Blog Index Page

### ISSUE THREAD

**Issue by TCKapGrp** [GSA/Challenge_gov#1313]
As a Challenge.Gov user,  when I navigate to the index page of the Challenge.Gov Blog https://www.challenge.gov/blog/, I would like to see a listing of all blog posts to easily get information.

Acceptance Criteria:

- [ ] Work with the PMO team and Product Owner to determine what content should be displayed on the blog index page
- [ ] Blog Page is Designed and Approved
- [ ] Page is coded and pushed to production

**Comment by r-bartlett-gsa** [comment]
Considering that there are currently 4 blog posts total, with the latest one published in 2021, I would like to propose a temp solution (all done through markdown and tag manager):

- Increase sidebar limit to ~10
- Update internal links from /blog to /blog/[link to latest post]
- Remove /blog from search results (but not child pages)
- Revisit after eval project is completed

**Comment by r-bartlett-gsa** [comment]
Will be closing this issue, because two new issues were created on challenges-and-prizes repo:

- https://github.com/GSA/challenges-and-prizes/issues/1944
- https://github.com/GSA/challenges-and-prizes/issues/1943
