### ISSUE TITLE
Definition of Done (DoD)

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_gov#1315]
As a Challenge.gov product team, in order to ensure the product features and updates we develop are secure, high quality and usable, we would like to establish a checklist of requirements we will follow as part of each user story.

Acceptance criteria:

- [x] A definition of done (DoD) is established (see example in comments below)
  - [x] A template is created for DoD checklist
  - [x] Define workflow checkpoints within DoD (what triggers the user story status updates)

**Comment by r-bartlett-gsa** [comment]
DoD Example:

- [ ] Code complete
  - [ ] Code does not introduce new design/tech debt
  - [ ] Code is organized appropriately  
  - [ ] Unit tests pass
  - [ ] No new bugs
- [ ] Tests coverage is greater than team benchmark (90% goal)
- [ ] Security scans passed
- [ ] Accessibility tested
  - [ ] Automated testing
  - [ ] Keyboard navigation
  - [ ] Focus confirmed
  - [ ] Color contrast compliance
  - [ ] Screen reader testing
- [ ] Build process and deployment is automated and repeatable 
- [ ] Load testing/performance testing 
- [ ] Documentation whenever possible
- [ ] Feature toggles if appropriate 
- [ ] Deployed to staging
- [ ] Usability testing
  - [ ] Cross browser testing (crossbrowsertesting.com?)
  - [ ] UI rendering is performant 
- [ ] PR approved / Peer reviewed
  - [ ] Code review
  - [ ] AC review
- [ ] PO / PM approved
  - [ ] AC is met and it works as expected

**Comment by r-bartlett-gsa** [comment]
For QA checklist (for consideration): https://docs.google.com/spreadsheets/d/1ocFFLkQl1wTVgD1BJwG1nifoNA_mOlqcCODkW8k6vCA/edit#gid=828822100

**Comment by r-bartlett-gsa** [comment]
Challenge.gov DoD: https://docs.google.com/document/d/1hVR1d5naOIZp1ynDmn2k8RE6OK8oTtzsC1EPV1MHMmw/edit?usp=sharing

**Comment by TCKapGrp** [comment]
@kkrug and/or @r-bartlett-gsa , the DoD is complete and located at https://docs.google.com/document/d/1hVR1d5naOIZp1ynDmn2k8RE6OK8oTtzsC1EPV1MHMmw/edit?usp=sharing.  Could you please create a template? Thank you!
