### ISSUE TITLE
Dependencies: Row 25

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_gov#1318]
As a Challenge.gov developer, in order to ensure our system and code are functioning correctly, I would like to address known dependencies. 

Acceptance Criteria / Task:
- [x] Item in row 25 is resolved, https://docs.google.com/spreadsheets/d/1SdOazTY5zIAS2BiLhd1cHdnXIFTypZK58nAwfMZqVQc/edit?usp=sharing

## QA Checklist:

Check that the application is fully functional and online, using the below checklist for reference:

+ [ ] **Visit the portal Challenge.gov** 
  - [x] Navigate to Challenge list 
  - [x] Filter by challenge options (challenge type) 
  - [x] Choose a challenge 
  - [x] Navigate through the tabs checking that options are render correctly 

+ [ ] **Login as Challenge Solver** 
  - [x] Choose one challenge 
  - [x] Send a submission   
  - [x] View the list of previous submission 
  - [x] Edit an active submission 

+ [ ] **Login as Challenge Admin**
  -  [x] Choose one challenge from the list
  -  [x] View the challenge 
  -  [x] Edit challenge 
  -  [x] Make small change and save 
  -  [x] Verify that you changes are visible on the front end 

+ [ ] **Login as Super Admin**  
  -  [x] Create a Challenge
  -  [x] Delete a Challenge
  -  [x] View Submitted Challenges
  -  [x] Download Challenge Submissions
  -  [x] Message Center 
  -  [x] View Analytics
  -  [x] View and Download Admin Reports (Admin)
  -  [x] View and Download PMO Reports (Admin)

**Comment by jdonis** [comment]
Comments & notes
https://docs.google.com/document/d/1rSryqAgm1x0SwDIkxT6hLNU5zEdLZzFJhSCyjToEW6w/edit
