### ISSUE TITLE
Dependencies: Row 44

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_gov#1319]
As a Challenge.gov developer, in order to ensure our system and code are functioning correctly, I would like to address known dependencies.

Acceptance Criteria / Task:

- [ ] Item in row 44 is resolved, https://docs.google.com/spreadsheets/d/1SdOazTY5zIAS2BiLhd1cHdnXIFTypZK58nAwfMZqVQc/edit?usp=sharing

**Comment by jdonis** [comment]
Quantum Validation assigned to me (@jdonis) 

**#QA Validation before sending to PROD** 

- [x] Challenge.gov is up and running in Staging and your able to login as any role 
- [x] Check is there's any error related to Quantum on the server log (cloud.gov) 

**QA Validation before after publish to PROD** 

- [x] Challenge.gov is up and running in Staging and your able to login as any role 
- [x] Check is there's any error related to Quantum on the server log (cloud.gov)

**Comment by jdonis** [comment]
Comments & notes 
https://docs.google.com/document/d/1wgWixYyytN2IVqa_YYCsFoy7HBJiYXuq9wK9bvz2mj0/edit?usp=sharing
