### ISSUE TITLE
QA Checklist

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_gov#1321]
As a Challenge.gov product team, in order to ensure the product features and updates we develop are secure, high quality and usable, we would like to establish a checklist of requirements we will follow as part of recuring tasks.

Acceptance criteria:

- [x] Task-specific QA checklists are established (example: App Restage, link to the doc is in the comment below)
- [x] QA checklists are added to appropriate backlog item templates

**Comment by r-bartlett-gsa** [comment]
@TCKapGrp Please share checklists that you used in Jira as an example.

**Comment by r-bartlett-gsa** [comment]
@kkrug Here's the document with QA list for restaging application: https://docs.google.com/document/d/1__2WJg-06x7Db959tHtisRyGeGi-dkG4pqI8ruYBQhw/edit?usp=sharing

**Comment by TCKapGrp** [comment]
> [@TCKapGrp](https://github.com/TCKapGrp) Please share checklists that you used in Jira as an example.

I shared this document with Kenny, but here is the list of workflows and styles that I was checking. https://docs.google.com/document/d/1j0yEmaLPu_5c4jev9UGH4lGsYxsbfNv1R5J0crJQWGc/edit?usp=sharing
