### ISSUE TITLE
Chrome Version Update

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_gov#1325]
As a DevOps engineer, in order to ensure the system is tested with Chrome browser, I need to update Chrome to latest version.

Acceptance criteria:

- [x] Chrome version is updated in CircleCi

**Comment by jdonis** [comment]
@r-bartlett-gsa @kkrug 

I created a new PR to push this change to PROD 
https://github.com/GSA/Challenge_gov/pull/1344
