### ISSUE TITLE
Document programming environment history and choices

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_gov#1326]
In order to provide future developers important context on the application and its various components, we want to document the historic selections, motivations, and decisions. 

Acceptance criteria:

- [ ] A document is created detailing historical and current technology choices, including programming languages and major frameworks.

**Comment by danivovich** [comment]
For review, the document described here https://docs.google.com/document/d/1Fnz9S-UYDPs3yeLTh_lrmWrxWTUrYo-m3pZaosBGujs/edit#heading=h.8nmkf02qttg6
