### ISSUE TITLE
Summarize Maintenance and Hosting Costs

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_gov#1328]
In order to make informed product decisions, we want to better understand short- and long-term O&M budget and cost implication of implementing evaluation capability (and technical decisions associated with it).

Acceptance criteria:

- [ ] Investigate and estimate the difference in hosting and maintenance costs of the various options being considered for the evaluations capability and future state of challenge.gov

**Comment by danivovich** [comment]
Document with this content https://docs.google.com/document/d/1aQE6L12Gf5dI-xChhqSK_7DqcBfY3PG4z70z7YrFX5E/edit#heading=h.7fgr8xssaupj
