### ISSUE TITLE
Spike and documentation on shared session between Phoenix and Rails

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_gov#1330]
In order to provide a seamless user experience, a login to the existing portal should translate to authentication of the new codebase/application. This will require securely sharing session details, session expiration, and idle time calculations between all components of the application. 

Acceptance criteria:

- [ ] A technical spike is conducted to test session sharing options and determine the integration between existing portal and new eval application.

**Comment by danivovich** [comment]
We have evaluated the technical feasibility and outlined the outcomes, open questions, and next steps. https://docs.google.com/document/d/1VjqhFCJzK7CpiZir85PLpAXkmcpVFaRXeRnHn3BxBWU/edit#heading=h.j5t14x227o7t
