### ISSUE TITLE
Create backlog for infrastructure changes to support evaluation

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_gov#1331]
In order to proceed with and track the progress of the technical work after the investigation regarding the integration of a Ruby on Rails codebase with the existing system is completed, we want to have tasks outlining the initial implementation work. 

Acceptance criteria:

- [x] An initial backlog of tasks to stand up Rails application integrated with the existing portal is written

**Comment by danivovich** [comment]
Sent level of effort estimate to @r-bartlett-gsa and @TCKapGrp via Slack.
