### ISSUE TITLE
Dependencies: row 5

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_gov#1358]
As a Challenge.gov developer, in order to ensure our system and code are functioning correctly, I would like to address known dependencies.

Acceptance Criteria / Task:

- [ ] Item in row 5 is resolved, https://docs.google.com/spreadsheets/d/1SdOazTY5zIAS2BiLhd1cHdnXIFTypZK58nAwfMZqVQc/edit?usp=sharing

**Comment by kkrug** [comment]
@jdonis It looks like all three environments (dev, staging, production) are currently on yarn version 1.22.5 according to the tool-versions files. Is this correct?
