### ISSUE TITLE
Dependencies: update jquery to 3.7.1

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_gov#1359]
As a Challenge.gov developer, in order to ensure our system and code are functioning correctly, I would like to address known dependencies.

Acceptance Criteria / Task:

- [ ] Item in row 69 is resolved, https://docs.google.com/spreadsheets/d/1SdOazTY5zIAS2BiLhd1cHdnXIFTypZK58nAwfMZqVQc/edit?usp=sharing

**Comment by jdonis** [comment]
Already in Staging , ready to deploy to PROD, no issues
