### ISSUE TITLE
New user role: Evaluator

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_gov#1360]
As a judge of federal prize competitions and challenges, in order to participate in the evaluation process for submissions of challenges on Challenge.gov, I would like to be able to access the portal with a specific role.

Acceptance criteria:

- [x] An admin user can assign an evaluator role to a user
  - [x] An evaluator role has the same rules and permissions as a challenge manager role
  - [x] An evaluator role does not have access to challenge management (anything in Phoenix app)

---
Current challenge manager role rules and permissions:

- access only with .gov or .mil email address
- requires approval by an admin user
- requires annual certification
- an admin user can give challenge manager access to non .gov/.mil accounts if a sponsorship/justification is provided by a federal employee, which is done outside of the platform

### Definition of Done

**Doing (dev team)**
- [x] Code complete 
- [x] Code is organized appropriately
- [x] Any known trade offs are documented in the associated GH issue
- [x] Code is documented, modules, shared functions, etc.
- [x] Automated testing has been added or updated in response to changes in this PR
- [x] The feature is smoke tested to confirm it meets requirements
- [x] Database changes have been peer reviewed for index changes and performance bottlenecks
- [ ] ~~PR that changes or adds UI~~
  - [ ] ~~include a screenshot of the WAVE report for the altered pages~~
  - [ ] ~~Confirm changes were validated for mobile responsiveness~~
- [x] PR approved / Peer reviewed 
- [x] Security scans passed
- [x] Automate accessibility tests passed
- [x] Build process and deployment is automated and repeatable
- [x] Feature toggles if appropriate
- [x] Deploy to staging
- [x] Move card to testing column in the board
---
**Staging**
- [x] Usability testing: mobile and desktop (Tracy or Marni)
- [ ] ~Accessibility tested (Marni)~
  - [ ]  ~Keyboard navigation~
  - [ ]  ~Focus confirmed~
  - [ ] ~Color contrast compliance~
  - [ ] ~Screen reader testing~
- [ ] ~Cross browser testing - UI rendering is performant on below listed devices/browsers (Tracy or Marni)~
  - [ ] ~Windows/Chrome~
  - [ ] ~Windows/Edge~
  - [ ] ~Mac/Chrome~
  - [ ] ~Mac/Safari~
  - [ ] ~iOS/Safari~
- [x] AC review (Renata)
- [ ] ~Deploy to production (production-like environment for eval capability) (dev team)~
- [x] Move to production column in the board
---
**Production**
- [ ] User and security documentation has been reviewed for necessary updates (Renata/Tracy/Dev team) 
- [x] PO / PM approved (Jarah or Renata)
- [x] AC is met and it works as expected (Jarah or Renata)
- [ ] Move to done column in the board (Jarah or Renata)

**Comment by mhotch24** [comment]
@r-bartlett-gsa User testing complete. Based on the AC no cross browser and A11y tests were preformed.
