### ISSUE TITLE
Challenge Portal Footer

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_gov#1363]
Note: This work needs to be deployed to [challenge portal eval dev environment](https://challenge-portal-eval-dev.app.cloud.gov/) ([challenge_gov repo > eval main branch](https://github.com/GSA/Challenge_gov/tree/eval-main))

### User Story
As a site user with challenge manager or public solver roles, in order to build my trust using challenge.gov site, I would like to see consistent branding and styling from any page of the site.

**Acceptance criteria:**

- [x] Challenge.gov footer is displayed for logged-in users using challenge management and submissions portal

### Definition of Done

**Doing (dev team)**
- [x] Code complete 
- [x] Code is organized appropriately
- [x] Any known trade offs are documented in the associated GH issue
- [x] Code is documented, modules, shared functions, etc.
~- [ ] Automated testing has been added or updated in response to changes in this PR~
- [x] The feature is smoke tested to confirm it meets requirements
~- [ ] Database changes have been peer reviewed for index changes and performance bottlenecks~
- [x] PR that changes or adds UI
  - [x] include a screenshot of the WAVE report for the altered pages
  - [x] Confirm changes were validated for mobile responsiveness
- [x] PR approved / Peer reviewed 
- [x] Security scans passed
~- [ ] Automate accessibility tests passed~
- [x] Build process and deployment is automated and repeatable
~- [ ] Feature toggles if appropriate~
- [x] Deploy to staging
- [x] Move card to testing column in the board
---
**Staging**
- [x] Accessibility tested (Marni)
  - [x]  Keyboard navigation
  - [x]  Focus confirmed
  - [ ] Color contrast compliance
  - [x] Screen reader testing 
- [x] Usability testing: mobile and desktop (Tracy or Marni)
- [x] Cross browser testing - UI rendering is performant on below listed devices/browsers (Tracy or Marni)
  - [x] Windows/Chrome
  - [x] Windows/Edge
  - [x] Mac/Chrome
  - [x] Mac/Safari
  - [x] iOS/Safari
- [x] AC review (Renata)
- [ ] ~Deploy to production (production-like environment for eval capability) (dev team)~
- [x] Move to production column in the board
---
**Production**
- [ ] ~User and security documentation has been reviewed for necessary updates (Renata/Tracy/Dev team)~ 
- [x] PO / PM approved (Jarah or Renata)
- [x] AC is met and it works as expected (Jarah or Renata)
- [x] Move to done column in the board (Jarah or Renata)

**Comment by r-bartlett-gsa** [comment]
![Image](https://github.com/user-attachments/assets/c65fb52e-fde7-4259-87e8-1061fd2a89a2)

Figma link: https://www.figma.com/design/VfdBFG8ShVnOStdSNYy9fR/Challenge.Gov-Component-Library?node-id=783-40675&t=OWoWYiIk449UTAiv-0

**Comment by r-bartlett-gsa** [comment]
Work progress document: https://docs.google.com/document/d/1m9GDKig5K_8mTU-F_xMwHaz7KfCrCLLX1_fGh-WqsCc/edit?usp=sharing

**Comment by jairoanaya** [comment]
Trade offs: no

Wave Report

![Image](https://github.com/user-attachments/assets/d7d212d3-7ae2-4db7-b144-c8924de1fdd6)


Responsive Evidence

![Image](https://github.com/user-attachments/assets/3ac67edc-170c-44b3-bbb1-bca8635b5f40)

**Comment by jairoanaya** [comment]
Work done:

- Code understanding from challenge_platform
- Code was adapted from challenge_platform
- Team feedback document created on Google - https://docs.google.com/document/d/1m9GDKig5K_8mTU-F_xMwHaz7KfCrCLLX1_fGh-WqsCc/edit?usp=drive_link
- Team feedback for implementation
- CSS update
- Testing in Desktop and Responsive
- Deploying into staging
- Feature ready for testing on staging
- Branch recreation from eval - new instruction
- Testing in Desktop and Responsive locally
- Feature ready for testing on eval-main staging (pending approved PR for deployment on eval staging)

Notes:

Due to a new branching instruction - a new branch was recreated from eval-main in order to deploy the feature into Eval version. Previous branches were deleted or archived.

**Comment by jairoanaya** [comment]
All manual validation passed. 
This card is ready to test on https://challenge-portal-eval-dev.app.cloud.gov/

**Comment by r-bartlett-gsa** [comment]
@jairoanaya Please check appropriate boxes in the Definition of Done list. If some of these items do not apply, please ~strike them out~. 
Here's a screenshot of that list: ![Image](https://github.com/user-attachments/assets/4df264b5-f8e8-42f5-af83-2a1d14d8cf7f)


Also, in you earlier comment you mention "Documentation created on Google". What does that mean?

**Comment by jairoanaya** [comment]
@r-bartlett-gsa Feedback has been addressed.

**Comment by mhotch24** [comment]
@r-bartlett-gsa All passed testing. The only "issues" are the font and location of Contact Us is slightly off and the GSA Challenge.gov watermark is smaller.

See comparison:
![Image](https://github.com/user-attachments/assets/8c5d7771-33af-418b-aadc-43f954497124)
![Image](https://github.com/user-attachments/assets/bdf3ea23-e610-4dc7-a4c9-432f991ada0d)
![Image](https://github.com/user-attachments/assets/1d9e89f2-c3f9-4c16-94c3-df927caf46b3)
![Image](https://github.com/user-attachments/assets/bf0f5f61-dfec-4aed-a644-f8f5a6fc7ef7)

**Comment by jairoanaya** [comment]
Scheduled for maintenance.

**Comment by r-bartlett-gsa** [comment]
@jairoanaya If you are referring to Marni's notes as scheduled for maintenance, please do not work on that at this time. We will address styling and design consistencies at a later time, during fit & finish stage before these updates go live. I consider this story as done.

**Comment by jairoanaya** [comment]
Yes. You are correct! I confirm that I will not work on this item at this time.
