### ISSUE TITLE
Challenge Portal Utility Menu

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_gov#1364]
Note: This work needs to be deployed to [challenge portal eval dev environment](https://challenge-portal-eval-dev.app.cloud.gov/) ([challenge_gov repo > eval main branch](https://github.com/GSA/Challenge_gov/tree/eval-main))

### User Story
As a challenger manager and/or a public solver using challenge management and submissions capability, in order to efficiently navigate the site, I would like easily accessible links/buttons that take me to the main functions of the authenticated sites.

**Acceptance criteria:**

- [x] Role-based navigation menu (utility nav menu) is displayed on each page of the Phoenix app
- [x] The utility nav menu reflects the same options as on the dashboard:
  - [x] #1388 (with an exception of Analytics and Message Center)
  - [x] ~#1389~ (Post-MVP)

**Development Tasks:**

- Links to the Portal App are configurable (Phoenix) [#140](https://github.com/GSA/Challenge_platform/issues/140)

### Definition of Done

**Doing (dev team)**
- [x] Code complete 
- [x] Code is organized appropriately
- [x] Any known trade offs are documented in the associated GH issue
~- [ ] Code is documented, modules, shared functions, etc.~
~- [ ] Automated testing has been added or updated in response to changes in this PR~
- [x] The feature is smoke tested to confirm it meets requirements
~- [ ] Database changes have been peer reviewed for index changes and performance bottlenecks~
- [x] PR that changes or adds UI
  - [x] include a screenshot of the WAVE report for the altered pages
  - [x] Confirm changes were validated for mobile responsiveness
- [x] PR approved / Peer reviewed 
- [x] Security scans passed
~- [ ] Automate accessibility tests passed~
- [x] Build process and deployment is automated and repeatable
~- [ ] Feature toggles if appropriate~
- [x] Deploy to staging
- [x] Move card to testing column in the board
---
**Staging**
- [x] Accessibility tested (Marni)
  - [x]  Keyboard navigation
  - [x]  Focus confirmed
  - [x] Color contrast compliance
  - [x] Screen reader testing 
- [x] Usability testing: mobile and desktop (Tracy or Marni)
- [x] Cross browser testing - UI rendering is performant on below listed devices/browsers (Tracy or Marni)
  - [x] Windows/Chrome
  - [x] Windows/Edge
  - [x] Mac/Chrome
  - [x] Mac/Safari
  - [x] iOS/Safari
- [x] AC review (Renata)
- [ ] ~Deploy to production (production-like environment for eval capability) (dev team)~
- [x] Move to production column in the board
---
**Production**
- [ ] ~User and security documentation has been reviewed for necessary updates (Renata/Tracy/Dev team)~ 
- [x] PO / PM approved (Jarah or Renata)
- [x] AC is met and it works as expected (Jarah or Renata)
- [x] Move to done column in the board (Jarah or Renata)

**Comment by r-bartlett-gsa** [comment]
Challenge manager:
![Image](https://github.com/user-attachments/assets/30527d1e-6e62-45a4-8807-75e7a5d055e5)

![Image](https://github.com/user-attachments/assets/5ae82b5e-3990-49b6-9c31-4a6ef0a07f63)

**Comment by r-bartlett-gsa** [comment]
Work progress document: https://docs.google.com/document/d/1_AvYWsmj3FlFgdlXcFNRA92pT_7unY68EhLNTf1xH9U/edit?usp=sharing

**Comment by jairoanaya** [comment]
Trade off: remove original header and incorporated into the Util Nav. Logout function kept. 

Responsive Evidence:
![Image](https://github.com/user-attachments/assets/f716bac5-a0bf-42fe-9e50-b05aae3e74e6)

![Image](https://github.com/user-attachments/assets/75704a6f-6f34-45c7-8f1f-ac85fafbe857)

WAVE Report
![Image](https://github.com/user-attachments/assets/bf8f638d-2062-4fee-b691-b0988dad3518)

**Comment by jairoanaya** [comment]
Work done:

- Code understanding from challenge_platform
- Code was adapted from challenge_platform
- Team feedback document created on Google - https://docs.google.com/document/d/1_AvYWsmj3FlFgdlXcFNRA92pT_7unY68EhLNTf1xH9U/edit?usp=drive_link
- Team feedback received for implementation
- CSS update
- Testing in Desktop and Responsive
- Deploying into staging
- Feature ready for testing on staging
- Branch recreation from eval - new instruction
- Testing in Desktop and Responsive locally
- Feature ready for testing on eval-main staging - https://challenge-portal-eval-dev.app.cloud.gov/

Notes:

Due to a new branching instruction - a new branch was recreated from eval-main in order to deploy the feature into Eval version. Previous branches were deleted or archived.

**Comment by r-bartlett-gsa** [comment]
@jairoanaya Same request as on the other stories, please review the Definition of Done.

And a question: when the dashboard will be updated with #1388, will the utility menu reflect new dashboard options?

**Comment by jairoanaya** [comment]
@r-bartlett-gsa feedback has been addressed.

Regarding #1388 , when this feature is implemented should reflect or affect the functionality of utility menu #1364 - expect additional questions regarding #1388.

**Comment by mhotch24** [comment]
@r-bartlett-gsa Testing complete.
