### ISSUE TITLE
Onboard Jay / Jairo

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_gov#1377]
- [x] Onboarding spreadsheet - Items assigned to new team member done
- [x] Onboarding spreadsheet complete 
- [x] Access and credentials for various accounts
- [x] Environment setup
- [x] Security training
  - [x] Privileged user (?)
- [x] GSA training

**Comment by TCKapGrp** [comment]
Spreadsheet: https://docs.google.com/spreadsheets/d/1PPd8efLQbD2-K3Tat0R77uc_djrX7eWry2j3bvr1JFk/edit?usp=sharing

Jay's Github acct is: https://github.com/jairoanaya.  Currently verifying setup is compliant with GSA requirements.

**Comment by TCKapGrp** [comment]
Met with Jay and showed him the Incident Response and Privileged User Documentation.
