### ISSUE TITLE
Process GSA Separations Report - June 2024

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_gov#1382]
As a Challenge.gov admin, in order to ensure only the active GSA employees have access to the platform, I would like the status of separated employees to be updated accordingly.

Acceptance criteria:

- [x] Review [GSA separation report for June, 2024](https://docs.google.com/spreadsheets/d/1hswfirjNQNUWIOYSx4Ee7shXl8naL2V9/edit?usp=drive_link&ouid=107603508579633019364&rtpof=true&sd=true) and compare it to Challenge.gov users list
- [x] Update the account status of separated employees as needed
- [ ] Document updated accounts

**Comment by TCKapGrp** [comment]
Hi @r-bartlett-gsa and @jarahameador, Separations Report Completed.  ONE match found in the "All leavers" tab and highlighted (red) in the document here: https://docs.google.com/spreadsheets/d/1hswfirjNQNUWIOYSx4Ee7shXl8naL2V9/edit?usp=drive_link&ouid=102935485655225894190&rtpof=true&sd=true.  I believe the process is that you deactivate, correct?  I'll make sure to document who deactivates in the SOP after I hear back from you.

**Comment by r-bartlett-gsa** [comment]
> Hi [@r-bartlett-gsa](https://github.com/r-bartlett-gsa) and [@jarahameador](https://github.com/jarahameador), Separations Report Completed. ONE match found in the "All leavers" tab and highlighted (red) in the document here: https://docs.google.com/spreadsheets/d/1hswfirjNQNUWIOYSx4Ee7shXl8naL2V9/edit?usp=drive_link&ouid=102935485655225894190&rtpof=true&sd=true. I believe the process is that you deactivate, correct? I'll make sure to document who deactivates in the SOP after I hear back from you.

@TCKapGrp The highlighted account was deactivated (It was decertified as of 7/25/24)
