### ISSUE TITLE
Update SMTP settings

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_gov#1386]
GSA is securing the simple mail transfer protocol (SMTP) service to ensure authorized access and implement uniform standards in the environment. These standards ensure a high level of service availability for all users and deliver the best possible customer experience when using GSA's SMTP service.

By **August 1, 2024**, all applications, alarms, or devices that use GSA’s SMTP email delivery service must have the correct SMTP settings to avoid delivery failures. 

Challenge.gov manages a service that will be impacted by this change.

Acceptance Criteria:

- [x] Register your server or application for new and continued SMTP service access to avoid service disruption of your application mail delivery:

    👉 [SMTP Server Info Update](https://lnks.gd/l/eyJhbGciOiJIUzI1NiJ9.eyJidWxsZXRpbl9saW5rX2lkIjoxMDAsInVyaSI6ImJwMjpjbGljayIsInVybCI6Imh0dHBzOi8vZG9jcy5nb29nbGUuY29tL2Zvcm1zL2QvZS8xRkFJcFFMU2NWTGw0bWJuNE04amxWWXhEZVJBREVoN2xuaVhEZGJiNWxhWE83N2hDRjNhVjFvdy92aWV3Zm9ybT91c3A9c2ZfbGluayIsImJ1bGxldGluX2lkIjoiMjAyNDA3MjIuOTc5Mjk5NDEifQ.1ENx_3MSdnOYhM19J0gkOG_9RgP8AKheeGwIr3qu580/s/905990578/br/246117124359-l)

- [x] Verify that the application mail delivery setting is configured correctly.

   👉 Use the same domain of the email address (ex: @[gsa.gov](http://gsa.gov/)) for the:

  - “Header From” field (the display - what the recipient sees in their inbox)
  - “Envelope From” field (communicated on the backend between servers)
  -  Update the sending email address to make it descriptive enough to identify what application or system is sending the message (e.g., [fas.mailer@gsa.gov](mailto:fas.mailer@gsa.gov)).

- [x] If you send emails using [DO-NOT-REPLY@gsa.gov](mailto:DO-NOT-REPLY@gsa.gov) or [donotreply@gsa.gov](mailto:donotreply@gsa.gov):

   👉 Change the sending email address to identify your system or application (e.g., [my_app_do_not_reply@gsa.gov](mailto:my_app_do_not_reply@gsa.gov)).

**Comment by jdonis** [comment]
@kkrug @r-bartlett-gsa 
For point one, let me know if you have any comments about the answers to the SMTP survey, attached a PDF with the answer.  If you're Ok I can send this information.  
https://drive.google.com/file/d/1PLz2xores_i_ZCiw0cjfOHNmGXGc_l3r/view?usp=sharing

Point 2 & 3 
https://docs.google.com/document/d/1XyK6buDAycFpPrgk3Ck__lxDWTLlDkFVwgZvTNnsSBI/edit?usp=sharing

**Comment by r-bartlett-gsa** [comment]
@jdonis All looks good to me. 

I just have one note, on the form please turn on "Send me a copy of my responses.", and then forward the email your receive to Kenny and me. Thank you!

**Comment by jdonis** [comment]
Email SMTP form confirmation 
https://drive.google.com/file/d/1WqTMFl_FdMl_N4xt68iSlMPgS7ddrFcJ/view?usp=sharing

**Comment by r-bartlett-gsa** [comment]
> Email SMTP form confirmation https://drive.google.com/file/d/1WqTMFl_FdMl_N4xt68iSlMPgS7ddrFcJ/view?usp=sharing

Thank you @jdonis! Can you please forward that email to me.
