### ISSUE TITLE
Challenger Manager's Dashboard (Phoenix)

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_gov#1388]
Note: This work needs to be deployed to [challenge portal eval dev environment](https://challenge-portal-eval-dev.app.cloud.gov/) ([challenge_gov repo > eval main branch](https://github.com/GSA/Challenge_gov/tree/eval-main))

### User Story
As an user with a challenge manager role, in order to know the full scope of site features available for my role, I would like a dashboard-like page that lists role-specific features.

**Acceptance Criteria:**

- [x] User with assigned challenge manager role can navigate to the following Challenge.gov features via a dashboard page on the Phoenix app:
  - [x] **Challenges**
    - [x] Takes the user to the Phoenix app where the user can manage challenges (existing feature)
  - [x] **Evaluation Forms**
    - [x] Takes the user to the Rails app where the user can create and manager evaluation forms, https://github.com/GSA/Challenge_platform/issues/60
    - [x] Temp link on eval dev: https://challenge-dev.app.cloud.gov/evaluation_forms
  - [x] **Submissions & Evaluations**
    - [x] Takes the user to the Rails app where the user can manage submissions and evaluation process, https://github.com/GSA/Challenge_platform/issues/59
    - [x] Temp link on eval dev: https://challenge-dev.app.cloud.gov/manage_submissions
  - [x] **Message center**
    - [x] Takes the user to the Phoenix app, where the user can access the existing Message Center section
  - [x] **Analytics**
    - [x] Takes the user to the Phoenix app, where the user can access the existing Analytics section
  - [x] **Resources**
    - [x] Takes the user to [the user guides content on challenge.gov website](https://www.challenge.gov/cm-user-guide/)

**Development tasks:**

- [ ] Task 1
- [ ] Task 2

### Definition of Done

**Doing (dev team)**
- [x] Code complete 
- [x] Code is organized appropriately
- [x] Any known trade offs are documented in the associated GH issue
- [x] Code is documented, modules, shared functions, etc.
~- [ ] Automated testing has been added or updated in response to changes in this PR~
- [x] The feature is smoke tested to confirm it meets requirements
~- [ ] Database changes have been peer reviewed for index changes and performance bottlenecks~
- [x] PR that changes or adds UI
  - [x] include a screenshot of the WAVE report for the altered pages
  - [x] Confirm changes were validated for mobile responsiveness
- [x] PR approved / Peer reviewed 
- [x] Security scans passed
- [x] Automate accessibility tests passed
- [x] Build process and deployment is automated and repeatable
~- [ ] Feature toggles if appropriate~
- [x] Deploy to staging
- [x] Move card to testing column in the board
---
**Staging**
- [x] Usability testing: mobile and desktop (Tracy or Marni)
- [ ] Accessibility tested (Marni)
  - [x]  Keyboard navigation
  - [x]  Focus confirmed
  - [x] Color contrast compliance
  - [ ] Screen reader testing 
- [ ] Cross browser testing - UI rendering is performant on below listed devices/browsers (Tracy or Marni)
  - [ ] Windows/Chrome
  - [ ] Windows/Edge
  - [x] Mac/Chrome
  - [x] Mac/Safari
  - [ ] iOS/Safari
- [x] AC review (Renata)
- [ ] ~Deploy to production (production-like environment for eval capability) (dev team)~
- [x] Move to production column in the board
---
**Production**
- [ ] ~User and security documentation has been reviewed for necessary updates (Renata/Tracy/Dev team)~ 
- [x] PO / PM approved (Jarah or Renata)
- [x] AC is met and it works as expected (Jarah or Renata)
- [x] Move to done column in the board (Jarah or Renata)

**Comment by r-bartlett-gsa** [comment]
![Image](https://github.com/user-attachments/assets/d808a523-5f47-4b25-834b-b68cadc59126)

![Image](https://github.com/user-attachments/assets/ed359fe6-0e57-4b27-b590-27d2462cdcf7)

**Comment by r-bartlett-gsa** [comment]
@stepchud Since this work was not started yet, should we move it to O&M team?

**Comment by jairoanaya** [comment]
@r-bartlett-gsa please address the following design validation in order to continue: https://docs.google.com/document/d/1oQvEK4wbFyvwNHswglthWheYlk2fdRrJryaudtk6068/edit?usp=drive_link

**Comment by r-bartlett-gsa** [comment]
@jairoanaya To answer your questions:

- Please use the designs provided in the comment above
- Yes, the side nav needs to be removed
- The links to `Submissions & Evaluations` and `Evaluation Forms` are provided in the acceptance criteria

**Comment by jairoanaya** [comment]
@r-bartlett-gsa to confirm:

The Submissions & Evaluation and Evaluation Forms links should be available to Admins also.
The internal header should be with H1 instead of H2 as shown in the images below to follow eval design pattern.
The util menu should be updated as well even if not listed in the acceptance criteria but shown in previous images.

![Image](https://github.com/user-attachments/assets/ba9ecb19-396a-495f-b1cf-1de71aa5b6d3)
![Image](https://github.com/user-attachments/assets/82632c9c-cf01-45f0-958f-dcad722ff99d)

**Comment by r-bartlett-gsa** [comment]
@jairoanaya Please see my answers below:

> The Submissions & Evaluation and Evaluation Forms links should be available to Admins also.

No, not at this time. While the design will change for Amin users, the dashboard options should not.

> The internal header should be with H1 instead of H2 as shown in the images below to follow eval design pattern.

Yes, the header should be H1, and it should say "Dashboard".

> The util menu should be updated as well even if not listed in the acceptance criteria but shown in previous images.

Yes, per our convo in #1364, the utility menu should reflect the dashboard options: https://github.com/GSA/Challenge_gov/issues/1364#issuecomment-2436320961

**Comment by jairoanaya** [comment]
Evidence of deployment:
WAVE Rerport

![Image](https://github.com/user-attachments/assets/daf0953b-84a4-408d-b513-174eb7d43747)
![Image](https://github.com/user-attachments/assets/3bdd5ff4-10bd-42ea-8a70-2514c6669e63)

Feature implemented:
Desktop 

Challenge manager
![Image](https://github.com/user-attachments/assets/bae73de7-08fb-47c4-a8eb-06bb25ad5ee3)


Non challenge manager
![Image](https://github.com/user-attachments/assets/cfdcbfef-9f1c-4daf-b585-e87a2aa7be8b)

Responsive
![Image](https://github.com/user-attachments/assets/572aa216-f6d0-4b3e-b1c5-2cd3cbed744d)
![Image](https://github.com/user-attachments/assets/79a702c4-f85d-43d4-8d05-26b5800a7b16)

Notice util nav is updated.
Feedback discussed on this card has been implemented.

Pending PR Acceptance and staging validation to close card.

**Comment by jairoanaya** [comment]
Work done:

- Code understanding from challenge_platform
- Code was adapted from challenge_platform
- Team feedback document created on Google - https://docs.google.com/document/d/1oQvEK4wbFyvwNHswglthWheYlk2fdRrJryaudtk6068/edit?usp=drive_link
- Team feedback received for implementation
- Feature implementation on dashboard, util nav and removing side nav. 
- CSS update
- Testing in Desktop and Responsive
- Deploying into staging https://challenge-portal-eval-dev.app.cloud.gov/
- Completing card Acceptance Criteria and required evidence of development
- Feature ready for testing on staging

**Comment by r-bartlett-gsa** [comment]
@jairoanaya Below is my feedback:

- For challenge manager role:
  - Remove dashboard page subtitle text "Engage with the features below to manage your workflows"
  - Change "Challenge management" to "Challenges", and remove "Create a new challenge"
  - Change Challenges card subtitle to "Create and manage your challenges."
  - Change "Help" to "Resources" and the subtitle to "Learn how to make the most of Challenge.gov and find support."
  - Add "Resources" to utility nav
  - Design screenshots for reference: https://github.com/GSA/Challenge_gov/issues/1388#issuecomment-2248866040
- For all user roles:
  - Mobile utility nav: add line break between icons and titles
  - Now that side nav is removed, either reduce the page width (as on rails app) or add side margins
 ![Image](https://github.com/user-attachments/assets/14a8264e-0d30-4ffe-9796-92807f40ef36)

**Comment by jairoanaya** [comment]
@r-bartlett-gsa I acknowledge the feedback. I expect to submit this feedback for PR on Monday 11/4 the latest.

**Comment by jairoanaya** [comment]
Feedback submitted for PR. Expecting PR acceptance.

**Comment by jairoanaya** [comment]
I confirm the latest updates is deployed on https://challenge-portal-eval-dev.app.cloud.gov/ and working as expected
You can see the PR here https://github.com/GSA/Challenge_gov/pull/1463

**Comment by r-bartlett-gsa** [comment]
Thank you @jairoanaya! Looks great.

**Comment by mhotch24** [comment]
@r-bartlett-gsa 

**Usability Findings:**
-  Upper case 'Center' in 'Message center' card
- Upper case 'Toolkit' in "Agency toolkit' card.

**Feature A11y finding:**
- Cards: Screenreader is blending card title right into supportive text. Try code semantically and put them in wrapping block level tags. Possibly wrap each line in a p or div tag, and then the screen reader will separate them properly.

**General A11y finding:**
- Skip to Main Content is not fully setup acrossRails and Eval-dev due to body content area not having appropriate ID: id="main-content".
- 'Find a Challenge' voices 'Active Challenges'. It needs to say 'Find a Challenge'.

**Comment by r-bartlett-gsa** [comment]
@jairoanaya Please address the following accessibility issue:

> Screenreader is blending card title right into supportive text. Try code semantically and put them in wrapping block level tags. Possibly wrap each line in a p or div tag, and then the screen reader will separate them properly.

**Comment by jairoanaya** [comment]
@r-bartlett-gsa @mhotch24 the following feedback has been implemented and deployed to https://challenge-portal-eval-dev.app.cloud.gov/

- Upper case 'Center' in 'Message center' card
- Upper case 'Toolkit' in "Agency toolkit' card.
- Screenreader is blending has been resolved.

Important: Voice over have been resolved on #1362 , id="main-content" I believe is not necessary, current behavior is consistent with eval. Please double check.
