### ISSUE TITLE
Archive Old Repos

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_gov#1396]
As a system stakeholder, in order to maintain an accurate list of system repos, I would like old repos that are no longer used to be archived.

Acceptance criteria:

- [x] The following repos are archived:
  - [x] https://github.com/GSA/Challenge_gov_SProxy
  - [x] https://github.com/GSA/Challenge_gov_CProxy
  - [x] https://github.com/GSA/challenge_gov_proxy
  - [x] https://github.com/GSA/ChallengeGov_FrontEnd

**Comment by kkrug** [comment]
@jdonis granted me access to SProxy and CProxy and both repos have been archived. https://github.com/GSA/challenge_gov_proxy throws a 404 error for both myself and Alejandro, meaning neither of us have access or it does not exist.

**Comment by kkrug** [comment]
https://github.com/GSA/ChallengeGov_FrontEnd is also an unused repo that I added to this ticket and have successfully archived
