### ISSUE TITLE
FIPS 199 Review and Update

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_gov#1399]
- [ ] Go over FIPS 199 with ISSO
- [ ] Review and update FIPS 199, system security impact level, to reflect changes to collected information:
  - [ ] [Working document](https://docs.google.com/document/d/1y5NaBOJCv9LcdoSGyNapJGTGWgTKpkVjR-n02cTiCnw/edit?usp=sharing)
  - [ ] [Official document ](https://docs.google.com/document/d/1yY9N_QAlFexGcsUXNaVsz26m-XZkSnE4glRr2CGjhKI/edit)

**Comment by jarahameador** [comment]
FIPS-199 has been completed and reviewed by the ISSO.  The ISSO will submit the FIPS-199 to Archer.
