### ISSUE TITLE
PTA Review and Update

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_gov#1400]
- [x] Review PTA, Privacy Threshold Analysis document, and update any changes to collected information:
  - [ ] [Working document](https://docs.google.com/document/d/13jkvXVlIFQB2TuEUd_-sq2c-YIoCHFcgIn9x_IXHfuI/edit)
  - [ ] [Official document](https://drive.google.com/file/d/1cnmCnYIlSm1lxcWQfJxnpp2yX6_qhPtm/view)
- [x] Once PTA is approved in Archer, verify PIA (Privacy Impact Assessment) determination
  - [x] If PIA is recommended, consult with ISSO for the next steps
- [x] Update the PTA working document to reflect changes in Archer

**Comment by jarahameador** [comment]
PTA was reviewed and a PIA was recommended.  PIA submitted on 8/7 to GSA Privacy office for review
