### ISSUE TITLE
PIA Submission

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_gov#1401]
- [x] As required by PTA determination, submit PIA
- [ ] Working document: https://docs.google.com/document/d/1AE_U1B4h6XBoVtL99UTW1QuL_uVYSqXK9MhnxzcSQ_E/edit?usp=sharing

**Comment by jarahameador** [comment]
PIA submitted to GSA privacy office for review on 8/7 - currently awaiting correspondence
