### ISSUE TITLE
SPIKE: Pending database engine version retirement and upgrades

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_gov#1438]
- [x] Review information provided in Cloud.gov support email (below)
- [x] Determine a path forward
- [x] Document proposed work

**Comment by r-bartlett-gsa** [comment]
Dear Cloud.gov customer,
 
We are reaching out to you because we were recently notified by AWS that there are pending retirements to the supported versions of RDS database engines for some of your databases hosted on Cloud.gov. Additionally there are pending updates for your database instances.
 
PostgreSQL major version 12 is being retired in February of 2025. We heavily recommend you do not wait for the scheduled forced upgrade date as this dramatically cuts down on the time to test your application for support of the upgrade. If you select to upgrade the database during a maintenance window, please note that it does involve some down time during the maintenance window. Additionally, if you elect to upgrade the database engine version during business hours please note it will involve some down time during business hours. Please review the options below.
 
To avoid possible downtime and handle these database engine version upgrades during the most convenient time for your applications, **please reply to this email to let us know which option you are selecting**:
 
1. **Heavily Recommended: Create a new db instance, migrate the data, test your application, delete the old db instance.**
There is tooling provided at https://github.com/cloud-gov/cg-manage-rds which shows how to import and export brokered databases
Additional information for PostgreSQL version 15 can be found at https://www.postgresql.org/docs/15/release-15.html#id-1.11.6.13.4
 
Please note for [PostgreSQL versions 15+ , using SSL is required when connecting to your database](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/PostgreSQL.Concepts.General.SSL.html#PostgreSQL.Concepts.General.SSL.Requiring). As such, you will need to configure your client library to use SSL when connecting to your database.
 
2. **Contact us and we will set the database instance to upgrade during the next maintenance window (Times are in UTC).**
 
3. **Contact us and we can schedule the upgrade during normal business hours.**
 
Your database services that need to be upgraded are:
Org | Space |  Instance name | Engine | Engine Version | Maintenance Window (UTC)
gsa-tts-innovation-challenge | dev | Challenge Portal Dev RDS | postgres | 12.17 | sat:11:24-sat:11:54
gsa-tts-innovation-challenge | staging | Challenge Portal Staging RDS | postgres | 12.17 | tue:08:31-tue:09:01

Your databases will be upgraded as per the upgrade path outlined in option 2, no earlier than February 10th, 2025 starting 12:00 AM (assuming you don’t choose to upgrade earlier) but please note that if a selection is not made by February 10th, your database engine version will be upgraded for you during the maintenance window.
 
There will be no increase in your Cloud.gov bill associated with these RDS PostgreSQL engine version upgrades. Currently, pricing for databases on Cloud.gov is based on storage volume. See https://cloud.gov/pricing/ for more information.
 
Please reply to this email with your choice of upgrades by February 1st, 2025 and let us know any questions or concerns that you have.
 
Thank you,
 
The Cloud.gov team

**Comment by kkrug** [comment]
See documentation here: https://docs.google.com/document/d/10HZ3opqdeYveKllbCciN6Jhdwf5Qs3NGaxOkY9EHJZQ/edit?usp=sharing
