### ISSUE TITLE
Vulnerability Investigation & Resolution

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_gov#1449]
- [x] Review the information shared below and resolve the identified vulnerability

---

**VDP alert -- Access Private Video With Password Stored On Bucket #2696411**

A public facing vulnerability has been identified via the GSA Vulnerability Disclosure Policy.

FISMA System: Q-Challenge
URL: https://s3.amazonaws.com/challenge-gov/wp-content/uploads/2016/09/Video-Details.txt
Finding Details:  A password-protected video is stored in the `[https://s3.amazonaws.com/challenge-gov/wp-content/uploads/2016/09/Video-Details.txt`](https://s3.amazonaws.com/challenge-gov/wp-content/uploads/2016/09/Video-Details.txt) bucket.
Severity: Medium

Steps to reproduce:
1- Go to https://s3.amazonaws.com/challenge-gov/wp-content/uploads/2016/09/Video-Details.txt
2- View the password-protected video path.
![Image](https://github.com/user-attachments/assets/68eb64ee-82b1-4aef-965a-54b823b9377b)

3- Entering the password at https://vimeo.com/video/183336589 grants you access to the video.
![Image](https://github.com/user-attachments/assets/a4d086c0-26cf-4831-8876-11526ed8dae4)

![Image](https://github.com/user-attachments/assets/fb5f2a7c-d566-4535-a7aa-6d48d619d418)

Impact Statement:
An attacker can access the video meant only for authorized users.

Please acknowledge receipt of this email and provide a technical point of contact to discuss the finding. In addition to resolving and responding to this vulnerability. During the mitigation process, please report any anomalous activity to the [GSA-IR@gsa.gov](mailto:GSA-IR@gsa.gov) inbox.

**Comment by r-bartlett-gsa** [comment]
Team discussion on slack: https://gsa-tts.slack.com/archives/GTETE7W82/p1729257942472519

**Comment by r-bartlett-gsa** [comment]
The file has been removed.
cc: @kkrug

**Comment by kkrug** [comment]
The file has been removed: ![Image](https://github.com/user-attachments/assets/07d44982-02c9-41b7-a582-7926597c8885)

There is also a ticket open to grant us access to the S3 bucket.
