### ISSUE TITLE
SSPP Table 10-4 Ports, Protocols, and Services: Review and Modify

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_gov#1472]
- [x] Review and update accordingly Ports, Protocols an Services table 10-4: https://docs.google.com/document/d/1aNzsU4lAqAMSpXecsSIMOG6dJN5Fo_fOoi1W-qu480s/edit?tab=t.0#heading=h.4k668n3

**Comment by danivovich** [comment]
@r-bartlett-gsa this is also done
